"""Seed data for darvinyi-library. Single source of truth for the queue and the
per-book prompt files. Regenerate queue.md and the NN-*.md prompts by running
_generate.py after editing this table.

Each book is a dict:
  id       stable slug used for filenames, registry id, and the page route
  title    book title
  author   author(s)
  year     first publication year (int, or approximate for ancient works)
  shelf    one of the 14 shelves
  tier     1 | 2 | 3
  thesis   one-line core argument, our words
  model    signature framework name, or "" if the book has no single one
  flag     credibility caveat to surface in "Where People Get It Wrong", or ""

Build order = stage, then the order within this list. STAGE_1 ids are the
launch shelf and build first regardless of tier position.
"""

# The 15-title launch shelf: highest reach, most diagrammable, defines each
# category in readers' minds. Built first.
STAGE_1 = [
    "atomic-habits", "thinking-fast-and-slow", "seven-habits", "how-to-win-friends",
    "sapiens", "mans-search-for-meaning", "psychology-of-money", "start-with-why",
    "mindset", "influence", "power-of-habit", "rich-dad-poor-dad", "deep-work",
    "never-split-the-difference", "subtle-art",
]

BOOKS = [
    # ------------------------------------------------------------------ Shelf 1
    # Behavioral Science & Decision-Making
    dict(id="thinking-fast-and-slow", title="Thinking, Fast and Slow", author="Daniel Kahneman", year=2011,
         shelf="Behavioral Science & Decision-Making", tier=1,
         thesis="Two modes of thought, one fast and intuitive, one slow and deliberate, govern how we judge and decide, and the fast one misleads us in systematic ways.",
         model="System 1 vs. System 2", flag=""),
    dict(id="influence", title="Influence: The Psychology of Persuasion", author="Robert Cialdini", year=1984,
         shelf="Behavioral Science & Decision-Making", tier=1,
         thesis="Compliance runs on a handful of deep psychological triggers that can be understood, spotted, and defended against.",
         model="Six principles of persuasion", flag=""),
    dict(id="predictably-irrational", title="Predictably Irrational", author="Dan Ariely", year=2008,
         shelf="Behavioral Science & Decision-Making", tier=1,
         thesis="Our irrational choices are not random; they follow predictable patterns we can anticipate.",
         model="", flag=""),
    dict(id="nudge", title="Nudge", author="Richard Thaler and Cass Sunstein", year=2008,
         shelf="Behavioral Science & Decision-Making", tier=1,
         thesis="How choices are arranged quietly steers the decisions people make, so design the architecture deliberately.",
         model="Choice architecture / the nudge", flag=""),
    dict(id="black-swan", title="The Black Swan", author="Nassim Nicholas Taleb", year=2007,
         shelf="Behavioral Science & Decision-Making", tier=1,
         thesis="History is dominated by rare, high-impact events that we cannot predict but insist on explaining after the fact.",
         model="Black swan events", flag=""),
    dict(id="superforecasting", title="Superforecasting", author="Philip Tetlock and Dan Gardner", year=2015,
         shelf="Behavioral Science & Decision-Making", tier=2,
         thesis="Forecasting is a skill: ordinary people who think in calibrated probabilities and update often beat experts.",
         model="", flag=""),
    dict(id="thinking-in-bets", title="Thinking in Bets", author="Annie Duke", year=2018,
         shelf="Behavioral Science & Decision-Making", tier=2,
         thesis="Good decisions and good outcomes are not the same thing; judge the decision, not the result.",
         model="Resulting", flag=""),
    dict(id="fooled-by-randomness", title="Fooled by Randomness", author="Nassim Nicholas Taleb", year=2001,
         shelf="Behavioral Science & Decision-Making", tier=2,
         thesis="We routinely mistake luck for skill because we see the winners and never count the invisible losers.",
         model="Survivorship bias", flag=""),
    dict(id="paradox-of-choice", title="The Paradox of Choice", author="Barry Schwartz", year=2004,
         shelf="Behavioral Science & Decision-Making", tier=2,
         thesis="More options can leave us less satisfied and more paralyzed, not freer.",
         model="Choice overload", flag=""),
    dict(id="blink", title="Blink", author="Malcolm Gladwell", year=2005,
         shelf="Behavioral Science & Decision-Making", tier=2,
         thesis="Snap judgments made in an instant can be as good as, and sometimes better than, careful analysis, but they also fail in specific ways.",
         model="Thin-slicing", flag=""),
    dict(id="misbehaving", title="Misbehaving", author="Richard Thaler", year=2015,
         shelf="Behavioral Science & Decision-Making", tier=3,
         thesis="The story of how economics was forced to admit that real humans, not rational agents, make its decisions.",
         model="", flag=""),
    dict(id="stumbling-on-happiness", title="Stumbling on Happiness", author="Daniel Gilbert", year=2006,
         shelf="Behavioral Science & Decision-Making", tier=3,
         thesis="We are strikingly bad at predicting what will make us happy, because imagination distorts the future in consistent ways.",
         model="Affective forecasting", flag=""),
    dict(id="noise", title="Noise", author="Daniel Kahneman, Olivier Sibony, and Cass Sunstein", year=2021,
         shelf="Behavioral Science & Decision-Making", tier=3,
         thesis="Unwanted variability in human judgment is a huge, hidden source of error, distinct from bias and just as costly.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 2
    # Habits & Productivity
    dict(id="atomic-habits", title="Atomic Habits", author="James Clear", year=2018,
         shelf="Habits & Productivity", tier=1,
         thesis="Tiny changes compound: build systems and identity rather than chasing goals, and let small habits accumulate into remarkable results.",
         model="Four laws of behavior change", flag=""),
    dict(id="power-of-habit", title="The Power of Habit", author="Charles Duhigg", year=2012,
         shelf="Habits & Productivity", tier=1,
         thesis="Habits run on a simple neurological loop, and understanding that loop is how you change them.",
         model="The habit loop", flag=""),
    dict(id="deep-work", title="Deep Work", author="Cal Newport", year=2016,
         shelf="Habits & Productivity", tier=1,
         thesis="The ability to focus without distraction on hard problems is rare, valuable, and trainable, and it is being destroyed by default modern work.",
         model="Deep vs. shallow work", flag=""),
    dict(id="seven-habits", title="The 7 Habits of Highly Effective People", author="Stephen Covey", year=1989,
         shelf="Habits & Productivity", tier=1,
         thesis="Lasting effectiveness comes from aligning yourself with timeless principles and working from the inside out, from private character to public collaboration.",
         model="The 7 habits", flag=""),
    dict(id="getting-things-done", title="Getting Things Done", author="David Allen", year=2001,
         shelf="Habits & Productivity", tier=2,
         thesis="Your mind is for having ideas, not holding them; get everything into a trusted external system and act from there.",
         model="Capture, clarify, organize, reflect, engage", flag=""),
    dict(id="essentialism", title="Essentialism", author="Greg McKeown", year=2014,
         shelf="Habits & Productivity", tier=2,
         thesis="Doing less but better, by disciplined pursuit of only what is essential, beats doing more of everything.",
         model="", flag=""),
    dict(id="flow", title="Flow", author="Mihaly Csikszentmihalyi", year=1990,
         shelf="Habits & Productivity", tier=2,
         thesis="The best moments come in a state of total absorption where challenge and skill are matched, and that state can be cultivated.",
         model="The flow channel", flag=""),
    dict(id="the-one-thing", title="The One Thing", author="Gary Keller and Jay Papasan", year=2013,
         shelf="Habits & Productivity", tier=2,
         thesis="Extraordinary results come from narrowing focus to the single most important task and letting it drive everything else.",
         model="The focusing question", flag=""),
    dict(id="four-thousand-weeks", title="Four Thousand Weeks", author="Oliver Burkeman", year=2021,
         shelf="Habits & Productivity", tier=2,
         thesis="A human life is absurdly short, and accepting that finitude, rather than fighting it with productivity, is the real task.",
         model="", flag=""),
    dict(id="make-time", title="Make Time", author="Jake Knapp and John Zeratsky", year=2018,
         shelf="Habits & Productivity", tier=3,
         thesis="Reclaim attention from an always-on world with small daily tactics built around a single chosen highlight.",
         model="Highlight, Laser, Energy, Reflect", flag=""),
    dict(id="indistractable", title="Indistractable", author="Nir Eyal", year=2019,
         shelf="Habits & Productivity", tier=3,
         thesis="Distraction starts inside us; master the internal triggers and the external ones lose their grip.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 3
    # Money, Investing & Economics
    dict(id="psychology-of-money", title="The Psychology of Money", author="Morgan Housel", year=2020,
         shelf="Money, Investing & Economics", tier=1,
         thesis="Doing well with money has little to do with intelligence and everything to do with behavior, patience, and knowing what enough means.",
         model="", flag=""),
    dict(id="rich-dad-poor-dad", title="Rich Dad Poor Dad", author="Robert Kiyosaki", year=1997,
         shelf="Money, Investing & Economics", tier=1,
         thesis="The wealthy buy assets that produce income while everyone else buys liabilities they mistake for assets.",
         model="Assets vs. liabilities",
         flag="Kiyosaki's specific financial advice is widely disputed by professionals, some anecdotes appear fictionalized, and parts promote high-risk approaches. Present the mindset, flag the specifics."),
    dict(id="intelligent-investor", title="The Intelligent Investor", author="Benjamin Graham", year=1949,
         shelf="Money, Investing & Economics", tier=1,
         thesis="Invest with a margin of safety and treat the market as a moody business partner, not a signal to obey.",
         model="Mr. Market / margin of safety", flag=""),
    dict(id="freakonomics", title="Freakonomics", author="Steven Levitt and Stephen Dubner", year=2005,
         shelf="Money, Investing & Economics", tier=1,
         thesis="If you follow the incentives, the hidden side of everyday life starts to make surprising sense.",
         model="Incentives", flag=""),
    dict(id="almanack-naval", title="The Almanack of Naval Ravikant", author="Eric Jorgenson", year=2020,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Build wealth through leverage and specific knowledge, and pursue happiness as a skill, not a destination.",
         model="Leverage and specific knowledge", flag=""),
    dict(id="think-and-grow-rich", title="Think and Grow Rich", author="Napoleon Hill", year=1937,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Sustained desire, faith, and persistence, organized into definite plans, are the engine behind wealth.",
         model="",
         flag="Hill's biographical and research claims (the supposed Carnegie commission, the 500 interviews) are historically doubted, and the mechanism is closer to motivation than method. Present as a mindset classic, not evidence."),
    dict(id="random-walk", title="A Random Walk Down Wall Street", author="Burton Malkiel", year=1973,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Markets are efficient enough that most active picking fails, so low-cost index funds are the rational default.",
         model="Efficient markets", flag=""),
    dict(id="millionaire-next-door", title="The Millionaire Next Door", author="Thomas Stanley and William Danko", year=1996,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Most real millionaires live frugally and invisibly; wealth is what you keep, not what you show.",
         model="", flag=""),
    dict(id="richest-man-babylon", title="The Richest Man in Babylon", author="George Clason", year=1926,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Timeless money rules told as parables: pay yourself first, live below your means, put money to work.",
         model="Pay yourself first", flag=""),
    dict(id="common-sense-investing", title="The Little Book of Common Sense Investing", author="John Bogle", year=2007,
         shelf="Money, Investing & Economics", tier=2,
         thesis="Owning the whole market cheaply and holding forever beats trying to beat it.",
         model="Index investing", flag=""),
    dict(id="your-money-or-your-life", title="Your Money or Your Life", author="Vicki Robin and Joe Dominguez", year=1992,
         shelf="Money, Investing & Economics", tier=3,
         thesis="Money is life energy; measure every purchase against the hours of life it costs.",
         model="Money as life energy", flag=""),
    dict(id="i-will-teach-you", title="I Will Teach You to Be Rich", author="Ramit Sethi", year=2009,
         shelf="Money, Investing & Economics", tier=3,
         thesis="Automate a simple system for spending, saving, and investing, then spend guilt-free on what you love.",
         model="Automated personal finance", flag=""),
    dict(id="capital-21c", title="Capital in the Twenty-First Century", author="Thomas Piketty", year=2013,
         shelf="Money, Investing & Economics", tier=3,
         thesis="When returns on capital outrun economic growth, wealth concentrates and inequality widens.",
         model="r > g", flag=""),
    dict(id="total-money-makeover", title="The Total Money Makeover", author="Dave Ramsey", year=2003,
         shelf="Money, Investing & Economics", tier=3,
         thesis="Get out of debt with a strict, emotional, step-by-step plan built on small early wins.",
         model="The debt snowball", flag=""),

    # ------------------------------------------------------------------ Shelf 4
    # Leadership & Business
    dict(id="how-to-win-friends", title="How to Win Friends and Influence People", author="Dale Carnegie", year=1936,
         shelf="Leadership & Business", tier=1,
         thesis="You move people not by argument but by genuine interest, appreciation, and letting them feel the idea is theirs.",
         model="", flag=""),
    dict(id="good-to-great", title="Good to Great", author="Jim Collins", year=2001,
         shelf="Leadership & Business", tier=1,
         thesis="Companies leap from good to great through humble, willful leadership, disciplined focus, and momentum that builds like a flywheel.",
         model="Level 5 Leadership / Hedgehog / Flywheel", flag=""),
    dict(id="start-with-why", title="Start With Why", author="Simon Sinek", year=2009,
         shelf="Leadership & Business", tier=1,
         thesis="People do not buy what you do, they buy why you do it, so great leaders and brands start from purpose.",
         model="The Golden Circle", flag=""),
    dict(id="lean-startup", title="The Lean Startup", author="Eric Ries", year=2011,
         shelf="Leadership & Business", tier=1,
         thesis="Build startups as experiments: ship a minimal version, measure real behavior, and learn fast enough to change course.",
         model="Build-measure-learn / MVP", flag=""),
    dict(id="zero-to-one", title="Zero to One", author="Peter Thiel", year=2014,
         shelf="Leadership & Business", tier=1,
         thesis="Real progress comes from building something genuinely new rather than copying what works, and monopolies, not competition, fund it.",
         model="0 to 1 vs. 1 to n", flag=""),
    dict(id="drive", title="Drive", author="Daniel Pink", year=2009,
         shelf="Leadership & Business", tier=1,
         thesis="For anything beyond rote work, real motivation comes from autonomy, mastery, and purpose, not carrots and sticks.",
         model="Autonomy, mastery, purpose", flag=""),
    dict(id="innovators-dilemma", title="The Innovator's Dilemma", author="Clayton Christensen", year=1997,
         shelf="Leadership & Business", tier=1,
         thesis="Great companies fail precisely by doing everything right for current customers while disruptive newcomers redefine the market beneath them.",
         model="Disruptive innovation", flag=""),
    dict(id="dare-to-lead", title="Dare to Lead", author="Brené Brown", year=2018,
         shelf="Leadership & Business", tier=2,
         thesis="Courageous leadership is built on vulnerability, clear values, and trust, not armor and authority.",
         model="", flag=""),
    dict(id="built-to-last", title="Built to Last", author="Jim Collins and Jerry Porras", year=1994,
         shelf="Leadership & Business", tier=2,
         thesis="Enduring great companies are built on a core ideology and audacious goals, not a single great leader or product.",
         model="BHAG", flag=""),
    dict(id="good-strategy", title="Good Strategy Bad Strategy", author="Richard Rumelt", year=2011,
         shelf="Leadership & Business", tier=2,
         thesis="Real strategy is a clear diagnosis, a guiding policy, and coherent action, not a list of goals and buzzwords.",
         model="Diagnosis, guiding policy, coherent action", flag=""),
    dict(id="hard-thing", title="The Hard Thing About Hard Things", author="Ben Horowitz", year=2014,
         shelf="Leadership & Business", tier=2,
         thesis="There is no formula for the hardest calls in building a company; there is only honesty, nerve, and doing the brutal thing well.",
         model="", flag=""),
    dict(id="blue-ocean", title="Blue Ocean Strategy", author="W. Chan Kim and Renée Mauborgne", year=2004,
         shelf="Leadership & Business", tier=2,
         thesis="Stop fighting in bloody red oceans of competition and create uncontested new market space instead.",
         model="Red vs. blue oceans", flag=""),
    dict(id="e-myth", title="The E-Myth Revisited", author="Michael Gerber", year=1995,
         shelf="Leadership & Business", tier=2,
         thesis="Most small businesses fail because the owner works in the business as a technician instead of on it as a system.",
         model="Work on it, not in it", flag=""),
    dict(id="extreme-ownership", title="Extreme Ownership", author="Jocko Willink and Leif Babin", year=2015,
         shelf="Leadership & Business", tier=2,
         thesis="Leaders own everything in their world, with no one else to blame, and that total responsibility is what makes teams win.",
         model="Extreme ownership", flag=""),
    dict(id="four-hour-workweek", title="The 4-Hour Workweek", author="Tim Ferriss", year=2007,
         shelf="Leadership & Business", tier=2,
         thesis="Escape the deferred-life plan by automating income and outsourcing work to buy back time now.",
         model="Define, Eliminate, Automate, Liberate", flag=""),
    dict(id="effective-executive", title="The Effective Executive", author="Peter Drucker", year=1966,
         shelf="Leadership & Business", tier=2,
         thesis="Effectiveness is a habit made of practices: managing time, focusing on contribution, and making decisions that matter.",
         model="", flag=""),
    dict(id="measure-what-matters", title="Measure What Matters", author="John Doerr", year=2018,
         shelf="Leadership & Business", tier=3,
         thesis="Align and stretch an organization by setting ambitious objectives paired with measurable key results.",
         model="OKRs", flag=""),
    dict(id="48-laws-of-power", title="The 48 Laws of Power", author="Robert Greene", year=1998,
         shelf="Leadership & Business", tier=3,
         thesis="Power follows observable, often ruthless laws, drawn from history, whether or not you choose to play by them.",
         model="", flag="An amoral catalog of manipulation presented descriptively. Frame as a lens on power dynamics, not an endorsement of the tactics."),
    dict(id="originals", title="Originals", author="Adam Grant", year=2016,
         shelf="Leadership & Business", tier=3,
         thesis="Original thinkers are not fearless prodigies; they doubt, procrastinate, and hedge, and still manage to champion new ideas.",
         model="", flag=""),
    dict(id="radical-candor", title="Radical Candor", author="Kim Scott", year=2017,
         shelf="Leadership & Business", tier=3,
         thesis="The best feedback comes from caring personally and challenging directly at the same time.",
         model="The candor matrix", flag=""),
    dict(id="culture-code", title="The Culture Code", author="Daniel Coyle", year=2018,
         shelf="Leadership & Business", tier=3,
         thesis="Strong group cultures are built deliberately through safety, shared vulnerability, and a clear sense of purpose.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 5
    # Communication & Relationships
    dict(id="nonviolent-communication", title="Nonviolent Communication", author="Marshall Rosenberg", year=1999,
         shelf="Communication & Relationships", tier=1,
         thesis="Conflict softens when we speak from observations, feelings, and needs, and make clear requests instead of demands.",
         model="Observation, feeling, need, request", flag=""),
    dict(id="crucial-conversations", title="Crucial Conversations", author="Kerry Patterson, Joseph Grenny, Ron McMillan, and Al Switzler", year=2002,
         shelf="Communication & Relationships", tier=1,
         thesis="High-stakes talks go well when you make it safe to say hard things and keep everyone contributing to a shared pool of meaning.",
         model="Pool of shared meaning", flag=""),
    dict(id="five-love-languages", title="The 5 Love Languages", author="Gary Chapman", year=1992,
         shelf="Communication & Relationships", tier=1,
         thesis="People give and receive love in different primary ways, and mismatched languages feel like absent love.",
         model="The five love languages", flag=""),
    dict(id="difficult-conversations", title="Difficult Conversations", author="Douglas Stone, Bruce Patton, and Sheila Heen", year=1999,
         shelf="Communication & Relationships", tier=2,
         thesis="Every hard conversation is really three at once: what happened, the feelings involved, and what it says about identity.",
         model="The three conversations", flag=""),
    dict(id="seven-principles-marriage", title="The Seven Principles for Making Marriage Work", author="John Gottman", year=1999,
         shelf="Communication & Relationships", tier=2,
         thesis="Lasting marriages are built on friendship, respect, and repair, and the warning signs of failure are measurable.",
         model="The Four Horsemen", flag=""),
    dict(id="made-to-stick", title="Made to Stick", author="Chip Heath and Dan Heath", year=2007,
         shelf="Communication & Relationships", tier=2,
         thesis="Ideas that stick share a recognizable set of traits, and you can engineer those traits on purpose.",
         model="SUCCESs", flag=""),
    dict(id="talking-to-strangers", title="Talking to Strangers", author="Malcolm Gladwell", year=2019,
         shelf="Communication & Relationships", tier=3,
         thesis="We are badly equipped to read people we do not know, and our default assumptions fail in dangerous ways.",
         model="", flag=""),
    dict(id="supercommunicators", title="Supercommunicators", author="Charles Duhigg", year=2024,
         shelf="Communication & Relationships", tier=3,
         thesis="Connection is a learnable skill: recognize what kind of conversation you are in and match it.",
         model="", flag=""),
    dict(id="attached", title="Attached", author="Amir Levine and Rachel Heller", year=2010,
         shelf="Communication & Relationships", tier=3,
         thesis="Adult attachment styles, secure, anxious, and avoidant, quietly shape how our relationships work.",
         model="Attachment styles", flag=""),

    # ------------------------------------------------------------------ Shelf 6
    # Negotiation
    dict(id="never-split-the-difference", title="Never Split the Difference", author="Chris Voss", year=2016,
         shelf="Negotiation", tier=1,
         thesis="Negotiation is emotional, not logical; win by making the other side feel understood through tactical empathy.",
         model="Mirroring, labeling, calibrated questions", flag=""),
    dict(id="getting-to-yes", title="Getting to Yes", author="Roger Fisher, William Ury, and Bruce Patton", year=1981,
         shelf="Negotiation", tier=1,
         thesis="Separate people from the problem and bargain over interests, not positions, to reach deals that actually hold.",
         model="Principled negotiation / BATNA", flag=""),
    dict(id="getting-past-no", title="Getting Past No", author="William Ury", year=1991,
         shelf="Negotiation", tier=3,
         thesis="Break through stonewalling, attacks, and tricks by refusing to react and building the other side a golden bridge.",
         model="", flag=""),
    dict(id="bargaining-for-advantage", title="Bargaining for Advantage", author="G. Richard Shell", year=1999,
         shelf="Negotiation", tier=3,
         thesis="Effective negotiation starts from knowing your own style and preparing around a few durable principles.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 7
    # Meaning, Psychology & the Mind
    dict(id="mans-search-for-meaning", title="Man's Search for Meaning", author="Viktor Frankl", year=1946,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="Even in the worst suffering we retain the freedom to choose our response, and finding meaning is what lets us endure.",
         model="Logotherapy", flag=""),
    dict(id="mindset", title="Mindset", author="Carol Dweck", year=2006,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="Believing ability is fixed or growable changes how you face challenge, effort, and failure, and shapes what you achieve.",
         model="Fixed vs. growth mindset", flag=""),
    dict(id="emotional-intelligence", title="Emotional Intelligence", author="Daniel Goleman", year=1995,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="Self-awareness, self-regulation, empathy, and social skill often matter more for a life than raw IQ.",
         model="The EI domains", flag=""),
    dict(id="grit", title="Grit", author="Angela Duckworth", year=2016,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="Sustained passion and perseverance toward long-term goals predicts success better than talent does.",
         model="Grit", flag=""),
    dict(id="body-keeps-the-score", title="The Body Keeps the Score", author="Bessel van der Kolk", year=2014,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="Trauma lives in the body and rewires the brain, so healing has to reach past talk into the nervous system.",
         model="", flag=""),
    dict(id="subtle-art", title="The Subtle Art of Not Giving a F*ck", author="Mark Manson", year=2016,
         shelf="Meaning, Psychology & the Mind", tier=1,
         thesis="A good life comes from choosing what to care about, accepting struggle, and dropping the demand to feel good all the time.",
         model="", flag=""),
    dict(id="quiet", title="Quiet", author="Susan Cain", year=2012,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Introverts bring strengths a loud, group-oriented culture overlooks, and honoring them changes how we work and live.",
         model="", flag=""),
    dict(id="happiness-hypothesis", title="The Happiness Hypothesis", author="Jonathan Haidt", year=2006,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Ancient wisdom about the good life holds up surprisingly well against modern psychology, once you see the mind as a rider on an elephant.",
         model="The elephant and the rider", flag=""),
    dict(id="flourish", title="Flourish", author="Martin Seligman", year=2011,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Well-being is more than happiness; it is built from positive emotion, engagement, relationships, meaning, and accomplishment.",
         model="PERMA", flag=""),
    dict(id="four-agreements", title="The Four Agreements", author="Don Miguel Ruiz", year=1997,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Four simple commitments about speech, reaction, and assumption can free you from self-imposed suffering.",
         model="The four agreements", flag=""),
    dict(id="twelve-rules", title="12 Rules for Life", author="Jordan Peterson", year=2018,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Meaning is found by taking on responsibility and imposing order at the edge of chaos, one rule at a time.",
         model="Order and chaos", flag=""),
    dict(id="feeling-good", title="Feeling Good", author="David Burns", year=1980,
         shelf="Meaning, Psychology & the Mind", tier=2,
         thesis="Moods follow thoughts, and learning to catch and correct distorted thinking can lift depression without drugs.",
         model="Cognitive distortions", flag=""),
    dict(id="talk-to-someone", title="Maybe You Should Talk to Someone", author="Lori Gottlieb", year=2019,
         shelf="Meaning, Psychology & the Mind", tier=3,
         thesis="Seen from both chairs, therapy reveals how change actually happens and how universal our struggles are.",
         model="", flag=""),
    dict(id="gifts-of-imperfection", title="The Gifts of Imperfection", author="Brené Brown", year=2010,
         shelf="Meaning, Psychology & the Mind", tier=3,
         thesis="Wholehearted living means letting go of who you think you should be and embracing worthiness as you are.",
         model="", flag=""),
    dict(id="lost-connections", title="Lost Connections", author="Johann Hari", year=2018,
         shelf="Meaning, Psychology & the Mind", tier=3,
         thesis="Much depression and anxiety stems from disconnection, from meaning, people, and nature, more than from brain chemistry alone.",
         model="", flag="Hari's downplaying of biological and genetic factors is contested by many researchers. Present the social thesis alongside that criticism."),
    dict(id="behave", title="Behave", author="Robert Sapolsky", year=2017,
         shelf="Meaning, Psychology & the Mind", tier=3,
         thesis="Every human behavior has causes stacked across timescales, from a neuron firing a second before to evolution over millennia.",
         model="Nested timescales of causation", flag=""),

    # ------------------------------------------------------------------ Shelf 8
    # Big Ideas: Science, History & Society
    dict(id="sapiens", title="Sapiens", author="Yuval Noah Harari", year=2011,
         shelf="Big Ideas: Science, History & Society", tier=1,
         thesis="Homo sapiens conquered the world because we alone cooperate flexibly in huge numbers around shared fictions like money, nations, and rights.",
         model="The three revolutions",
         flag="Harari's sweeping synthesis draws sharp criticism from specialists for overstatement and factual slips. Present the big-picture argument while noting scholars contest specific claims."),
    dict(id="guns-germs-steel", title="Guns, Germs, and Steel", author="Jared Diamond", year=1997,
         shelf="Big Ideas: Science, History & Society", tier=1,
         thesis="The broad shape of history was set by geography and biology, not by any innate differences between peoples.",
         model="Geographic determinism",
         flag="Many anthropologists and historians consider the thesis overly deterministic and selective. Present the argument alongside the specialist critique."),
    dict(id="outliers", title="Outliers", author="Malcolm Gladwell", year=2008,
         shelf="Big Ideas: Science, History & Society", tier=1,
         thesis="Extraordinary success is less about lone genius than about hidden advantages, timing, culture, and accumulated hours of practice.",
         model="The 10,000-hour rule",
         flag="The 10,000-hour rule is a simplification the original researcher (Ericsson) has publicly disputed. Note the gap between the slogan and the science."),
    dict(id="selfish-gene", title="The Selfish Gene", author="Richard Dawkins", year=1976,
         shelf="Big Ideas: Science, History & Society", tier=1,
         thesis="Evolution is best understood from the gene's point of view: bodies are vehicles genes build to copy themselves.",
         model="The gene's-eye view / the meme", flag=""),
    dict(id="short-history-nearly-everything", title="A Short History of Nearly Everything", author="Bill Bryson", year=2003,
         shelf="Big Ideas: Science, History & Society", tier=1,
         thesis="The whole sweep of science, from the Big Bang to human origins, told as a curious amateur's grand tour.",
         model="", flag=""),
    dict(id="homo-deus", title="Homo Deus", author="Yuval Noah Harari", year=2015,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="Having largely tamed famine, plague, and war, humanity's next project is upgrading itself toward god-like powers, with data as the new authority.",
         model="Dataism", flag=""),
    dict(id="cosmos", title="Cosmos", author="Carl Sagan", year=1980,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="A luminous tour of the universe and our tiny, precious place in it, told through the story of how we came to know it.",
         model="", flag=""),
    dict(id="brief-history-time", title="A Brief History of Time", author="Stephen Hawking", year=1988,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="Space, time, black holes, and the origin of the universe, made graspable without equations.",
         model="", flag=""),
    dict(id="the-gene", title="The Gene", author="Siddhartha Mukherjee", year=2016,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="The story of the gene, from Mendel's peas to gene editing, and the promise and peril of rewriting ourselves.",
         model="", flag=""),
    dict(id="why-nations-fail", title="Why Nations Fail", author="Daron Acemoglu and James Robinson", year=2012,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="Prosperity depends on inclusive institutions that share power and opportunity, while extractive ones keep nations poor.",
         model="Inclusive vs. extractive institutions", flag=""),
    dict(id="factfulness", title="Factfulness", author="Hans Rosling", year=2018,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="The world is better than we think, and our gloom comes from instincts that a fact-based worldview can correct.",
         model="Ten instincts", flag=""),
    dict(id="emperor-maladies", title="The Emperor of All Maladies", author="Siddhartha Mukherjee", year=2010,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="A biography of cancer across millennia: how we have understood, fought, and slowly gained ground against it.",
         model="", flag=""),
    dict(id="henrietta-lacks", title="The Immortal Life of Henrietta Lacks", author="Rebecca Skloot", year=2010,
         shelf="Big Ideas: Science, History & Society", tier=2,
         thesis="One woman's cells, taken without consent, transformed medicine and expose the ethics and race at the heart of science.",
         model="", flag=""),
    dict(id="silent-spring", title="Silent Spring", author="Rachel Carson", year=1962,
         shelf="Big Ideas: Science, History & Society", tier=3,
         thesis="Unchecked pesticide use was poisoning the living world, a warning that launched the modern environmental movement.",
         model="", flag=""),
    dict(id="sixth-extinction", title="The Sixth Extinction", author="Elizabeth Kolbert", year=2014,
         shelf="Big Ideas: Science, History & Society", tier=3,
         thesis="Humanity is driving a mass extinction on the scale of the great die-offs of deep time.",
         model="", flag=""),
    dict(id="astrophysics-hurry", title="Astrophysics for People in a Hurry", author="Neil deGrasse Tyson", year=2017,
         shelf="Big Ideas: Science, History & Society", tier=3,
         thesis="The essentials of the cosmos, from the Big Bang to dark matter, in brisk and vivid brief chapters.",
         model="", flag=""),
    dict(id="demon-haunted-world", title="The Demon-Haunted World", author="Carl Sagan", year=1995,
         shelf="Big Ideas: Science, History & Society", tier=3,
         thesis="Science is a candle in the dark, and skeptical thinking is our best defense against superstition and deception.",
         model="The baloney detection kit", flag=""),

    # ------------------------------------------------------------------ Shelf 9
    # Systems, Complexity & the Future
    dict(id="thinking-in-systems", title="Thinking in Systems", author="Donella Meadows", year=2008,
         shelf="Systems, Complexity & the Future", tier=1,
         thesis="Most problems are system problems, and learning to see stocks, flows, and feedback loops reveals where real leverage lies.",
         model="Stocks, flows, feedback, leverage points", flag=""),
    dict(id="range", title="Range", author="David Epstein", year=2019,
         shelf="Systems, Complexity & the Future", tier=1,
         thesis="In complex, unpredictable fields, broad generalists who sample widely often outperform narrow early specialists.",
         model="", flag=""),
    dict(id="antifragile", title="Antifragile", author="Nassim Nicholas Taleb", year=2012,
         shelf="Systems, Complexity & the Future", tier=2,
         thesis="Some things gain from disorder; the goal is not just to survive shocks but to be built so they make you stronger.",
         model="Fragile, robust, antifragile", flag=""),
    dict(id="fifth-discipline", title="The Fifth Discipline", author="Peter Senge", year=1990,
         shelf="Systems, Complexity & the Future", tier=2,
         thesis="Organizations thrive when they learn, and systems thinking is the discipline that binds the others together.",
         model="The learning organization", flag=""),
    dict(id="the-innovators", title="The Innovators", author="Walter Isaacson", year=2014,
         shelf="Systems, Complexity & the Future", tier=3,
         thesis="The digital revolution was made by collaboration across generations, not by lone geniuses.",
         model="", flag=""),
    dict(id="superintelligence", title="Superintelligence", author="Nick Bostrom", year=2014,
         shelf="Systems, Complexity & the Future", tier=3,
         thesis="If machine intelligence surpasses ours, controlling it becomes the defining challenge, and we are unprepared.",
         model="The control problem", flag=""),
    dict(id="scientific-revolutions", title="The Structure of Scientific Revolutions", author="Thomas Kuhn", year=1962,
         shelf="Systems, Complexity & the Future", tier=3,
         thesis="Science does not advance smoothly but lurches through revolutions that overturn whole paradigms.",
         model="Paradigm shift", flag=""),
    dict(id="godel-escher-bach", title="Gödel, Escher, Bach", author="Douglas Hofstadter", year=1979,
         shelf="Systems, Complexity & the Future", tier=3,
         thesis="Mind and meaning emerge from self-reference and strange loops, patterns shared by logic, art, and music.",
         model="Strange loops", flag=""),

    # ------------------------------------------------------------------ Shelf 10
    # Philosophy & Wisdom
    dict(id="meditations", title="Meditations", author="Marcus Aurelius", year=180,
         shelf="Philosophy & Wisdom", tier=1,
         thesis="A Roman emperor's private notes on duty, mortality, and mastering the only thing in our control: our own judgments.",
         model="", flag=""),
    dict(id="obstacle-is-the-way", title="The Obstacle Is the Way", author="Ryan Holiday", year=2014,
         shelf="Philosophy & Wisdom", tier=1,
         thesis="Every obstacle contains the way forward if you meet it with clear perception, decisive action, and steady will.",
         model="Perception, action, will", flag=""),
    dict(id="daily-stoic", title="The Daily Stoic", author="Ryan Holiday and Stephen Hanselman", year=2016,
         shelf="Philosophy & Wisdom", tier=2,
         thesis="A year of short Stoic meditations turning ancient philosophy into a daily practice.",
         model="", flag=""),
    dict(id="tao-te-ching", title="Tao Te Ching", author="Lao Tzu", year=-400,
         shelf="Philosophy & Wisdom", tier=2,
         thesis="Live in accord with the Tao by yielding, simplifying, and acting without forcing.",
         model="Wu wei", flag=""),
    dict(id="letters-from-a-stoic", title="Letters from a Stoic", author="Seneca", year=65,
         shelf="Philosophy & Wisdom", tier=2,
         thesis="Warm, practical letters on time, wealth, fear, and death from a Stoic who lived at the center of power.",
         model="", flag=""),
    dict(id="ego-is-the-enemy", title="Ego Is the Enemy", author="Ryan Holiday", year=2016,
         shelf="Philosophy & Wisdom", tier=2,
         thesis="At every stage, aspiration, success, and failure, ego is the enemy, and humility is the discipline that beats it.",
         model="", flag=""),
    dict(id="guide-to-good-life", title="A Guide to the Good Life", author="William Irvine", year=2008,
         shelf="Philosophy & Wisdom", tier=3,
         thesis="A practical modern program of Stoic techniques for reducing anxiety and wanting what you already have.",
         model="Negative visualization", flag=""),
    dict(id="art-of-war", title="The Art of War", author="Sun Tzu", year=-500,
         shelf="Philosophy & Wisdom", tier=3,
         thesis="The highest skill is to win without fighting, through preparation, positioning, and knowing yourself and your rival.",
         model="", flag=""),
    dict(id="tao-of-pooh", title="The Tao of Pooh", author="Benjamin Hoff", year=1982,
         shelf="Philosophy & Wisdom", tier=3,
         thesis="The principles of Taoism, explained through the effortless wisdom of Winnie-the-Pooh.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 11
    # Spirituality & Mindfulness
    dict(id="power-of-now", title="The Power of Now", author="Eckhart Tolle", year=1997,
         shelf="Spirituality & Mindfulness", tier=1,
         thesis="Most suffering comes from being lost in thought about past and future; freedom is found in the present moment.",
         model="", flag=""),
    dict(id="untethered-soul", title="The Untethered Soul", author="Michael Singer", year=2007,
         shelf="Spirituality & Mindfulness", tier=2,
         thesis="You are not the anxious voice in your head but the awareness watching it, and noticing that changes everything.",
         model="", flag=""),
    dict(id="wherever-you-go", title="Wherever You Go, There You Are", author="Jon Kabat-Zinn", year=1994,
         shelf="Spirituality & Mindfulness", tier=2,
         thesis="Mindfulness is simply paying full attention to the present, on purpose and without judgment, and it can be practiced anywhere.",
         model="", flag=""),
    dict(id="miracle-of-mindfulness", title="The Miracle of Mindfulness", author="Thich Nhat Hanh", year=1975,
         shelf="Spirituality & Mindfulness", tier=3,
         thesis="Even washing the dishes can be a meditation when done with full, gentle awareness.",
         model="", flag=""),
    dict(id="waking-up", title="Waking Up", author="Sam Harris", year=2014,
         shelf="Spirituality & Mindfulness", tier=3,
         thesis="Spiritual experience and the loss of the sense of self can be explored honestly, without religion.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 12
    # Learning & Skill Acquisition
    dict(id="peak", title="Peak", author="Anders Ericsson and Robert Pool", year=2016,
         shelf="Learning & Skill Acquisition", tier=1,
         thesis="Expertise is not a gift but the product of deliberate practice: focused, effortful, feedback-driven work at the edge of ability.",
         model="Deliberate practice", flag=""),
    dict(id="make-it-stick", title="Make It Stick", author="Peter Brown, Henry Roediger, and Mark McDaniel", year=2014,
         shelf="Learning & Skill Acquisition", tier=2,
         thesis="The learning that feels easy is the least durable; real learning comes from retrieval, spacing, and desirable difficulty.",
         model="Retrieval, spacing, interleaving", flag=""),
    dict(id="ultralearning", title="Ultralearning", author="Scott Young", year=2019,
         shelf="Learning & Skill Acquisition", tier=2,
         thesis="You can master hard skills fast through aggressive, self-directed projects built on a few core principles.",
         model="", flag=""),
    dict(id="moonwalking-einstein", title="Moonwalking with Einstein", author="Joshua Foer", year=2011,
         shelf="Learning & Skill Acquisition", tier=3,
         thesis="Extraordinary memory is a trainable technique, not a gift, and the ancient method of loci is its heart.",
         model="The memory palace", flag=""),
    dict(id="mind-for-numbers", title="A Mind for Numbers", author="Barbara Oakley", year=2014,
         shelf="Learning & Skill Acquisition", tier=3,
         thesis="Learning hard subjects gets easier when you alternate focused effort with diffuse rest and work with how the brain actually learns.",
         model="Focused vs. diffuse thinking", flag=""),

    # ------------------------------------------------------------------ Shelf 13
    # Creativity & Writing
    dict(id="big-magic", title="Big Magic", author="Elizabeth Gilbert", year=2015,
         shelf="Creativity & Writing", tier=1,
         thesis="Creative living means chasing curiosity instead of fear, and treating inspiration as a partner rather than a burden.",
         model="", flag=""),
    dict(id="steal-like-an-artist", title="Steal Like an Artist", author="Austin Kleon", year=2012,
         shelf="Creativity & Writing", tier=1,
         thesis="Nothing is fully original; creativity is remixing influences you love into something recognizably your own.",
         model="", flag=""),
    dict(id="on-writing", title="On Writing", author="Stephen King", year=2000,
         shelf="Creativity & Writing", tier=1,
         thesis="Good writing is a craft learned by reading widely, writing daily, and cutting without mercy, told through one writer's life.",
         model="", flag=""),
    dict(id="bird-by-bird", title="Bird by Bird", author="Anne Lamott", year=1994,
         shelf="Creativity & Writing", tier=2,
         thesis="You get through writing, and life, one small piece at a time, and you give yourself permission to write badly first.",
         model="Shitty first drafts", flag=""),
    dict(id="war-of-art", title="The War of Art", author="Steven Pressfield", year=2002,
         shelf="Creativity & Writing", tier=2,
         thesis="A hidden force called Resistance sabotages every creative act, and beating it means simply turning pro and showing up.",
         model="Resistance", flag=""),
    dict(id="artists-way", title="The Artist's Way", author="Julia Cameron", year=1992,
         shelf="Creativity & Writing", tier=2,
         thesis="Creativity can be recovered through steady practices that quiet the inner critic and refill the well.",
         model="Morning pages and artist dates", flag=""),
    dict(id="creative-act", title="The Creative Act", author="Rick Rubin", year=2023,
         shelf="Creativity & Writing", tier=3,
         thesis="Creativity is a way of being, a practice of paying attention and getting out of the work's way.",
         model="", flag=""),
    dict(id="show-your-work", title="Show Your Work!", author="Austin Kleon", year=2014,
         shelf="Creativity & Writing", tier=3,
         thesis="Get discovered by sharing your process openly and generously, not by hoarding finished work.",
         model="", flag=""),

    # ------------------------------------------------------------------ Shelf 14
    # Health & the Body
    dict(id="why-we-sleep", title="Why We Sleep", author="Matthew Walker", year=2017,
         shelf="Health & the Body", tier=1,
         thesis="Sleep is not optional downtime but the foundation of health, memory, and mood, and modern life is starving us of it.",
         model="",
         flag="Independent reviewers have documented factual errors and at least one likely misleading graph in the book. Present the core message that sleep matters while noting specific claims have been credibly challenged."),
    dict(id="breath", title="Breath", author="James Nestor", year=2020,
         shelf="Health & the Body", tier=2,
         thesis="How we breathe, and especially breathing through the nose, quietly shapes health more than we realize.",
         model="", flag=""),
    dict(id="outlive", title="Outlive", author="Peter Attia", year=2023,
         shelf="Health & the Body", tier=2,
         thesis="Living longer and better means shifting medicine from reacting to disease toward preventing it decades early.",
         model="Medicine 3.0", flag=""),
    dict(id="how-not-to-die", title="How Not to Die", author="Michael Greger", year=2015,
         shelf="Health & the Body", tier=3,
         thesis="Diet is the biggest lever against the diseases most likely to kill us, and the evidence points toward whole plant foods.",
         model="",
         flag="Greger presents a strongly pro-plant case and some critics argue the evidence is read selectively. Present the dietary argument as one well-supported view, not settled fact."),
    dict(id="omnivores-dilemma", title="The Omnivore's Dilemma", author="Michael Pollan", year=2006,
         shelf="Health & the Body", tier=3,
         thesis="Tracing our food back to its source reveals how industrial eating disconnects us from what we consume.",
         model="", flag=""),
    dict(id="when-breath-becomes-air", title="When Breath Becomes Air", author="Paul Kalanithi", year=2016,
         shelf="Health & the Body", tier=3,
         thesis="A young neurosurgeon facing terminal cancer asks what makes a life worth living when time runs short.",
         model="", flag=""),
]

# Sanity: STAGE_1 ids must all exist in BOOKS.
_ids = {b["id"] for b in BOOKS}
_missing = [i for i in STAGE_1 if i not in _ids]
assert not _missing, f"STAGE_1 ids not found in BOOKS: {_missing}"
assert len(_ids) == len(BOOKS), "duplicate id in BOOKS"
